### ISSUE TITLE
Tofu 1.7 won't start on iOS 12.4.1

### ISSUE THREAD

**Issue by jonasstrandstedt** [calleerlandsson/Tofu#37] opened 2020-02-23 17:55 UTC
After upgrading to Tofu 1.7 it crashes directly after starting it on iPhone 6S running iOS 12.4.1.

**Comment by calleerlandsson** [comment] 2020-02-23 20:29
Oh no! Thanks for reporting this @jonasstrandstedt. In an attempt to stop automatic updates and prevent more people from getting the version that crashes on launch on iOS 12, I have removed the app from sale on the AppStore.

I'll try to get a fixed version submitted for review tomorrow. Hopefully, I can have it out within a few days.

Would you be willing to join the TestFlight beta program to help test new versions for iOS 12 compatibility? If so, send me an email on calle@calleerlandsson.com and I'll reply with an invitation.

**Comment by jonasstrandstedt** [comment] 2020-02-24 06:59
Sure, I'll help out if I can. I have sent an email.

**Comment by fnowak** [comment] 2020-02-24 09:09
The same is happening on an iPhone 5S running iOS 12.4.5.

**Comment by calleerlandsson** [comment] 2020-02-24 09:16
Thanks for the report @fnowak.

**Status update:** I have identified and fixed the cause of the crash and have submitted a new build both for beta and AppStore review. As soon as the beta review is done, the new build will be available to TestFlight testers. After confirming the fix and waiting for AppStore review I will put the app back on the AppStore.

**Comment by calleerlandsson** [comment] 2020-02-24 19:35
This issue was fixed in 93766b0b04ba6530e4a216f4a2b2e9da259f9442 that is part of version 1.8. I have just released this version and put the app back on the AppStore so it should be available within a few hours.

**Closed by calleerlandsson** 2020-02-24 19:35 UTC
